### ISSUE TITLE
networkAccessAllowed

### ISSUE THREAD

**Issue by mythodeia** [ArcRain/AMPhotoLibrary#4]
For images that need to be downloaded from the iCloud/PhotoStream the PHImageRequestOptions need to include the following:
``` request.networkAccessAllowed = YES; ```
i think the default is NO so by adding this we can get the online images as well.
Do you think this can be added as well?
thanks for your time

**Comment by ArcRain** [comment]
I'll consider to implement this feature. 
Thanks for your advice.

**Comment by mythodeia** [comment]
thanks :+1:

**Comment by ArcRain** [comment]
I have updated code today for this feature. I added a method for async mode. You can try it now~ :-)
+ (void)fetchAsset:(AMPhotoAsset *)asset withImageType:(AMAssetImageType)imageType imageResult:(void(^)(UIImage *image))resultBlock;

**Comment by mythodeia** [comment]
i will check it out later today. thanks
