### ISSUE TITLE
mainThread

### ISSUE THREAD

**Issue by mythodeia** [ArcRain/AMPhotoLibrary#5]
for the method 
``` - (void)enumerateAlbums:(AMPhotoManagerAlbumEnumerationBlock)enumerationBlock resultBlock:(AMPhotoManagerResultBlock)resultBlock{ ```
i think the resultBlock should be sent on mainThread, right?
```
            dispatch_async(dispatch_get_main_queue(), ^{
                resultBlock(success, error);
            });
```
thanks for making this library available. Great work

**Comment by ArcRain** [comment]
I think it's not MUST. Because that is not thread safety when ALAssetsLibrary and PHPhotoLibrary perform function and run callback block.

**Comment by mythodeia** [comment]
ok , the only reason i mentioned this is because the result block of the method below will make updates to the UI, which is supposed to be done on mainThread.
```
 [[AMPhotoLibrary sharedPhotoLibrary] enumerateAlbums:^(AMPhotoAlbum *album, BOOL *stop) {
      [tempArray addObject: album];
 } resultBlock:^(BOOL success, NSError *error) {
     // mainThread UI update
}];
```

**Comment by ArcRain** [comment]
It's a mistake in my sample code. :-)  I forgot to consider thread safety in UI code.
I will do some code review again.
Thanks a lot!

**Comment by mythodeia** [comment]
thanks :+1:

**Comment by ArcRain** [comment]
Add block tips in header file
