### ISSUE TITLE
photoLibraryDidChange in albums view

### ISSUE THREAD

**Issue by mythodeia** [ArcRain/AMPhotoLibrary#6]
Hello
i am using 
```
- (void)photoLibraryDidChange:(PHChange *)changeInstance{
```
to get info when the datasource changes.
this works well when i am inside the thumbs view.

however i have a view with albums before the thumbs one and in that view i show the album title and the number of files inside each album. I want to be able to show the updated count of files when a files is added or removed. 
e.g the user backgrounds the app and adds or removes a file from camera roll or from whichever albums he owns. Then comes back to the app. Its then that i would like to update the cound.
Is there a way to get changes using the method above?

thanks

**Comment by ArcRain** [comment]
Thanks for your feed back.
I've updated my code and demo for this issue. You can try again.

**Comment by mythodeia** [comment]
amazing support my friend. Thanks a lot for your time! :+1:
