### ISSUE TITLE
Video Feature - not an issue

### ISSUE THREAD

**Issue by mythodeia** [ArcRain/AMPhotoLibrary#7]
Currently the demo shows the image in the PhotoDetailViewController.
if the user selects video the view is blank since it only supports images.
I know its not an issue or a bug. 
I only wanted to point out that it would make this library (demo) complete 
if it would support showing videos too.
Again i must point out that its not something necessary.Just a feature
Other than that excellent work :+1:

**Comment by ArcRain** [comment]
I will consider to implent it in my free time.  :-)

**Comment by ArcRain** [comment]
I've done. Now, you can try again~:-)

**Comment by mythodeia** [comment]
@ArcRain thanks so much for your time on this feature. 
i tested it and all i see is a blank screen. Are you able to play videos in your device?
Try the following:
record 1 normal video and 1 slow motion. Test both of them.
In my device none of them work.

**Comment by ArcRain** [comment]
@mythodeia I fixed an issue about video file URL and add a new property 'localIdentifier' for asset properties.
Please update again, it will be OK.

**Comment by mythodeia** [comment]
it works on normal videos just fine! thanks!

However on slow motion videos this ```PHVideoRequestOptionsVersionCurrent``` found in your code [here](https://github.com/ArcRain/AMPhotoLibrary/blob/master/AMPhotoLibrary/AMPhotoLibrary/AMPhotoAsset.m#L482)
 causes a crash. 
if you change it to ```PHVideoRequestOptionsVersionOriginal``` it works but the video plays like its fast forward. 
i do not know how if there is a solution for this.

**Comment by ArcRain** [comment]
I will try to fix it. Give me some time. :-)

**Comment by ArcRain** [comment]
@mythodeia Please update code. I fixed the crash issue and play slow motion issue on iOS 8+.
When playing slow motion videos, we should use AVPlayer instead of MPMoviePlayerController.
It plays well with PhotoKit, but wrong with ALAssetsLibrary.

**Comment by mythodeia** [comment]
amazing support! excellent code! :+1:

**Comment by ArcRain** [comment]
Thanks. On what aspect？We can contact with email. :-)

**Comment by mythodeia** [comment]
@ArcRain check your email
